spring.application.name=Apigateway
server.port=8111

eureka.client.registerWithEureka=true
eureka.client.fetchRegistry=true


# Define the routes for the API Gateway

# Route for the user service
spring.cloud.gateway.routes[0].id=DataquadRequirementsApi
spring.cloud.gateway.routes[0].uri=lb://DataquadRequirementsApi
spring.cloud.gateway.routes[0].predicates[0]=Path=/requirements/**

